### ISSUE TITLE
bacularis-standalone: Autochanger storage config option modified by itself

### ISSUE THREAD

**Issue by kibeb** [bacularis/bacularis-docker#3]
I suspect there is an error in form configuring storage, e.g. `/web/storage/1/#storage_config`. 

Steps to reproduce:
1. Checkbox called **Autochanger** always displays as unchecked after loading this form. 
2. Then, if I don't change anything and just click **Save**, the configuration changes, Autochanger is now set to "No" in the table view. 
3. If I open the Details again, click Configure storage, enable/check Autochanger option and save, it's now set to "Yes" in the table view.
4. I can open the same Details again and repeat from step 2.

And I'm thinking... would this be a systematic error and there are more checkboxes like this one? IDK, but it's scary -- so many options, it's somewhat overwhelming. 

(I used image: bacularis/bacularis-standalone:latest downloaded from Docker Hub on 2022-11-30.)

Thanks.

**Comment by ganiuszka** [comment]
Hello kibeb,

Thank you for this bug report. Yes, you are right that there is a problem with this checkbox. I have checked it. It is because the ``Autochanger`` directive is not only boolean type (``yes/no``) but it can also take Storage resource name. From this reason ``bdirjson`` for value ``yes`` displays the current resource name instead of ``yes`` and it causes this bug.

Below is the example:

In bacula-dir.conf we have ``Autochanger = yes``:
```
Storage {
  Name = "FileChanger1"
  Address = "10.0.0.146"
  Password = "xxxx"
  Device = "FileChgr1"
  MediaType = "File1"
  MaximumConcurrentJobs = 4
  Autochanger = yes
}
```

but bdirjson returns FileChanger1:

```
bdirjson -n FileChanger1
```

```
[
{
  "Storage": {
    "Name": "FileChanger1",
    "Address": "10.0.0.146",
    "Password": "xxxx",
    "Device": ["FileChgr1"],
    "MediaType": "File1",
    "Autochanger": "FileChanger1",
    "MaximumConcurrentJobs": 4
  }
}
]
```

I will fix it. Thanks again.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello kibeb,

This bug has been fixed. Now the autochanger directive is combobox and can take storage resource name or 'yes' value. The 'yes' is shortcut to the current storage resource.

Thanks for your help.

Best regards,
Marcin Haba (gani)
