### ISSUE TITLE
Add Dockerfile for Debian Trixie / Bacula 13.0.4-1 ?

### ISSUE THREAD

**Issue by karlkashofer** [bacularis/bacularis-docker#4]
Hi !

Any chance you could include a docker container using Debian Trixie which contains Bacula 13.0.4 ?

Thanks,
KK

**Comment by ganiuszka** [comment]
Hello @karlkashofer

Thank you for your question.

Yes, it seems to be a very good point that Bacula in Bookwork is very old.

OK, we will try to prepare images based on Trixie. We are planning a new release Bacularis ``2.7.0`` very soon so we will prepare it for this ``2.7.0``.

So far for Debian images we have been using Bookworm because it is stable.

I will keep this issue open and let you know when it is ready.

Thanks!

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @karlkashofer,

I am glad to let you know that the Docker images with Debian ``13`` Trixie and Bacula ``13.0.4`` are available already in the Docker Hub repositories. They are with the latest Bacularis ``2.7.0`` released at the moment.

Thanks!

Best regards,
Marcin Haba (gani)

**Comment by karlkashofer** [comment]
I am impressed ! Very cool !
Will test asap,
cheers,
KK
