### ISSUE TITLE
Help with setting up Bacularis in existing docker compose Bacula environment

### ISSUE THREAD

**Issue by mblataric** [bacularis/bacularis-docker#9]
Hi, 

I really like look and feel of Bacularis, so I thought I will add it to existing Bacula environment running in docker compose stack (multi-container application). 

However, I can not figure out how to do this. I can easily install bacularis-web, but I have no idea how to install and setup Bacularis API instances in existing environment and existing API docker images have Bacula services built-in, not using existing ones. 

Only thing I managed to find regarding that is in the docs:
 _If you would like to use Bacularis instance in container with Bacula components located outside the container, you need to prepare it yourself._

But ... how? :-) 

Since all services are running in same stack, networking and volume mapping is easy, so it should not be a problem to allow Bacularis access Bacularis conf file, but it all seems way too complex for my level of knowledge on the subject. 

Could you please provide some more information how to install Bacularis in existing docker Bacularis stack? 

Thanks, 
Mario

**Comment by ganiuszka** [comment]
Hello Mario ( @mblataric ),

The question that you asked is a question that I am thinking since time when I have started learning Docker few years ago :smile: I don't have any ready answer, but I will try to give you some tips.

The key problem in separating Bacularis and Bacula in different containers is that Bacularis API needs the direct access to Bacula configuration files. So, if you would like to have a container image that provides Bacularis only, you need to mount or bind inside this container the Bacula configuration stored from the Bacula containers.

Second problem is with reloading the Bacula configuration. For Bacula Director it isn't a problem because the configuration is reloaded through the bconsole ``reload`` command. But for FD/SD it requires restarting the Bacula components. In this case in the Bacularis API actions you may need to provide remote comands that will restart the components remotely on the Bacula containers.

I wish you good luck with setting it up :smile: 

Best regards,
Marcin Haba (gani)

**Comment by mblataric** [comment]
Hi, 

thanks for quick reply. 

Ok, first thing that confuses me is Bacularis API, because I do not see a docker image - except API images with Bacula components integrated. 

So, my step 1 questions are:
 1. Which docker image do I use as Bacularis API?
 2. My current Bacula cointainers have config files in /opt/bacula/etc - where do I need to mount them in Bacularis API container? 

Thanks, 
Mario

**Comment by ganiuszka** [comment]
Hi Mario (@mblataric),

Yes, this API concept can be confusing. We were trying to describe it in the Bacularis documentation but it is not easy topic to understand in general.

Below you can find answers on the questions:

For 1) In the Bacularis Project we don't provide the pure Bacularis API container images, as you correctly noticed. So, the answer is - these API container images do not exist.

For 2) You can mount them everywhere you want in the Bacularis API container. It can be ``/opt/bacula/etc`` or any other path. The most important is after mounting it to define these config files in the Bacularis API settings (it is ``api.conf``).

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hi Mario (@mblataric),

Because help has been provided, I am closing this issue.

Good luck with the Bacularis container images.

Best regards,
Marcin Haba (gani)
